version: "3.5"

services:

  #--------------------------------------------------------------------------------------------------------------------
  # Traefik
  #--------------------------------------------------------------------------------------------------------------------
  traefik:
    container_name: traefik
    hostname: traefik
    domainname: ${LDAP_DOMAIN}
    image: traefik:2.3.7
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`docker01-traefik.${LDAP_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal

      - traefik.http.routers.traefik-http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.traefik-http-catchall.entrypoints=http
      - traefik.http.routers.traefik-http-catchall.middlewares=traefik-redirect-to-https@docker
      - traefik.http.middlewares.traefik-redirect-to-https.redirectscheme.scheme=https
    command:
      # - --log.level=DEBUG
      - --api=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entryPoints.https.address=:443
      - --providers.file.directory=/config/
      - --providers.file.watch=true
      - --metrics.prometheus=false
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${DATA_DIR}/traefik/config:/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-proxy
    extra_hosts: 
      - host.docker.internal:172.17.0.1

  #--------------------------------------------------------------------------------------------------------------------
  # LDAP
  #--------------------------------------------------------------------------------------------------------------------
  kopano_ldap:
    image: osixia/openldap:latest
    hostname: kopano_ldap
    container_name: kopano_ldap
    domainname: ${LDAP_DOMAIN}
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_LOG_LEVEL=0
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      - LDAP_READONLY_USER=true
    command: "--copy-service"
    volumes:
      - ./ldap/schema:/container/service/slapd/assets/config/bootstrap/schema
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ${DATA_DIR}/ldap/data:/var/lib/ldap
      - ${DATA_DIR}/slapd/data:/etc/ldap/slapd.d
    healthcheck:
      test: ["CMD-SHELL", 'ldapsearch -H ldap://127.0.0.1:389 -D cn=readonly,$$LDAP_BASE_DN -b cn=readonly,$$LDAP_BASE_DN -w $$LDAP_READONLY_USER_PASSWORD']
      interval: 1m
      timeout: 10s
    ports:
      - 389:389
    networks:
      - traefik-proxy

  traefik-proxy:
    external: true
